#                    12345678
ln -s c-convert.c    c-conver.c
ln -s c-aux-info.c   c-aux-in.c
ln -s print-tree.c   print-tr.c
ln -s stor-layout.c  stor-lay.c
ln -s fold-const.c   fold-con.c
ln -s print-rtl.c    print-rt.c
ln -s integrate.c    integrat.c
ln -s local-alloc.c  local-al.c
ln -s global-alloc.c global-a.c
ln -s caller-save.c  caller-s.c
ln -s insn-peep.c    insn-pee.c
ln -s reg-stack.c    reg-stac.c
ln -s insn-recog.c   insn-rec.c
ln -s insn-extract.c insn-ext.c
ln -s insn-output.c  insn-out.c
ln -s insn-emit.c    insn-emi.c
ln -s insn-attrtab.c insn-att.c
ln -s aux-output.c   aux-outp.c
