/* @(#)event.h	1.1 2/17/92 */
typedef unsigned char GAZ_EVENT;

#define GAZ_EVENT_UNDEFINED		0x01

#define GAZ_EVENT_BREAKPOINT    	0x02
#define GAZ_EVENT_REG_WRITE		0x02

#define GAZ_EVENT_PORT		0x04

#define GAZ_EVENT_INTERNAL		0x08

#define GAZ_EVENT_INACTIVE		0x10

#define GAZ_EVENT_COMPAND		0x20

#define GAZ_EVENT_EXISTS		0x40

#define GAZ_EVENT_ROM		0x80
#define GAZ_EVENT_PIN_DRIVEN	0x80

#define UDEF		(GAZ_EVENT)GAZ_EVENT_UNDEFINED
#define REG_WRITE	(GAZ_EVENT)GAZ_EVENT_REG_WRITE
#define PIN_DRIVEN	(GAZ_EVENT)GAZ_EVENT_PIN_DRIVEN
