.\" -----------------------------------
.TH MEM21K 1 \"20 Oct 1999\" \"Release 3.3 Version 2.30\"
.SH NAME
mem21k \- Analog Devices ADSP-210x0 Initializer

.SH SYNOPSIS
.B mem21k
[
.I options
]
.I infile

.SH OPTIONS
.TP
\fB-a\fP \fIfile\fP
Specify architecture file.
.TP
\fB-h\fP
Display usage.
.TP
\fB-o\fP \fIfile\fP
Specify output file name.
.TP
\fB-v\fP
Verbose.

.SH "BUGS"
.PP
This man page needs more work.

.SH "COPYRIGHT"
Copyright (c) 1991-1997 Analog Devices, Inc.
.PP
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.
.PP
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

.SH "SEE ALSO"
.IR ld21k (1)

